[package]
name = "lottery"
version = "0.0.1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-stdlib"

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
lottery = "0x1234"
admin_address = "0xad1"
zabava = "0x5678"